export const EXAM_DATE = '2026-08-17';
export const CHART_START = '2026-05-04';

export const TASKS = [
  // Phase 1 (id 1–44)
  { id: 1,  phase: 1, title: 'Endocrinology — Consolidation · Pass 2 · Master Sheet',  subject: 'Endocrinology', eQty: 40, isMilestone: true },
  { id: 2,  phase: 1, title: 'Cardiology 1 — Watch · Notes',                            subject: 'Cardiology',    eQty: 10, isMilestone: false },
  { id: 3,  phase: 1, title: 'Cardiology 2 — Watch · Notes',                            subject: 'Cardiology',    eQty: 10, isMilestone: false },
  { id: 4,  phase: 1, title: 'ECG 1 — Watch · Notes',                                   subject: 'Cardiology',    eQty: 10, isMilestone: false },
  { id: 5,  phase: 1, title: 'Cardiology Q Solve — Watch · Notes',                      subject: 'Cardiology',    eQty: 10, isMilestone: false },
  { id: 6,  phase: 1, title: 'Cardiology — Consolidation · Pass 2 · Master Sheet',      subject: 'Cardiology',    eQty: 40, isMilestone: true },
  { id: 7,  phase: 1, title: 'Pediatrics 1 — Watch · Notes',                            subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 8,  phase: 1, title: 'Pediatrics 2 — Watch · Notes',                            subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 9,  phase: 1, title: 'Pediatrics 3 — Watch · Notes',                            subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 10, phase: 1, title: 'Pediatrics 4 — Watch · Notes',                            subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 11, phase: 1, title: 'Pedi Special Problem 1 — Watch · Notes',                  subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 12, phase: 1, title: 'Pedi Q Solve 1 — Watch · Notes',                          subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 13, phase: 1, title: 'Pedi Q Solve 2 — Watch · Notes',                          subject: 'Pediatrics',    eQty: 10, isMilestone: false },
  { id: 14, phase: 1, title: 'Pediatrics — Consolidation · Pass 2 · Master Sheet',      subject: 'Pediatrics',    eQty: 40, isMilestone: true },
  { id: 15, phase: 1, title: 'Surgery — Watch · Notes',                                 subject: 'Surgery',       eQty: 40, isMilestone: true },
  { id: 16, phase: 1, title: 'Respiratory 1 — Watch · Notes',                           subject: 'Respiratory',   eQty: 10, isMilestone: false },
  { id: 17, phase: 1, title: 'Respiratory 2 — Watch · Notes',                           subject: 'Respiratory',   eQty: 10, isMilestone: false },
  { id: 18, phase: 1, title: 'Respiratory — Q Solve · Consolidation',                   subject: 'Respiratory',   eQty: 40, isMilestone: true },
  { id: 19, phase: 1, title: 'Orthopedics 1 — Watch · Notes',                           subject: 'Orthopedics',   eQty: 10, isMilestone: false },
  { id: 20, phase: 1, title: 'Psychiatry 1 — Watch · Notes',                            subject: 'Psychiatry',    eQty: 10, isMilestone: false },
  { id: 21, phase: 1, title: 'Psychiatry 2 — Watch · Notes',                            subject: 'Psychiatry',    eQty: 10, isMilestone: false },
  { id: 22, phase: 1, title: 'Psychiatry 3 — Watch · Notes',                            subject: 'Psychiatry',    eQty: 10, isMilestone: false },
  { id: 23, phase: 1, title: 'Psychiatry — Q Solve · Consolidation',                    subject: 'Psychiatry',    eQty: 40, isMilestone: true },
  { id: 24, phase: 1, title: 'ENT — Watch · Notes',                                     subject: 'ENT',           eQty: 40, isMilestone: true },
  { id: 25, phase: 1, title: 'GIT 1 — Watch · Notes',                                   subject: 'GIT',           eQty: 10, isMilestone: false },
  { id: 26, phase: 1, title: 'GIT 2 — Watch · Notes · Consolidation',                   subject: 'GIT',           eQty: 40, isMilestone: true },
  { id: 27, phase: 1, title: 'Ophthalmology — Watch · Notes',                           subject: 'Ophthalmology', eQty: 40, isMilestone: true },
  { id: 28, phase: 1, title: 'Gynae 1 — Watch · Notes',                                 subject: 'Obs/Gynae',     eQty: 10, isMilestone: false },
  { id: 29, phase: 1, title: 'Gynae 2 — Watch · Notes',                                 subject: 'Obs/Gynae',     eQty: 10, isMilestone: false },
  { id: 30, phase: 1, title: 'Obstetrics 1 — Watch · Notes',                            subject: 'Obs/Gynae',     eQty: 10, isMilestone: false },
  { id: 31, phase: 1, title: 'Obstetrics 2 — Watch · Notes',                            subject: 'Obs/Gynae',     eQty: 10, isMilestone: false },
  { id: 32, phase: 1, title: 'O&G — Consolidation · Pass 2 · Master Sheet',             subject: 'Obs/Gynae',     eQty: 40, isMilestone: true },
  { id: 33, phase: 1, title: 'Neurology — Watch · Notes',                               subject: 'Neurology',     eQty: 40, isMilestone: true },
  { id: 34, phase: 1, title: 'Orthopedics 2 — Watch · Notes',                           subject: 'Orthopedics',   eQty: 40, isMilestone: true },
  { id: 35, phase: 1, title: 'Rheumatology 1 — Watch · Notes',                          subject: 'Rheum/Renal',   eQty: 10, isMilestone: false },
  { id: 36, phase: 1, title: 'Rheum + Renal 2 — Watch · Notes',                         subject: 'Rheum/Renal',   eQty: 10, isMilestone: false },
  { id: 37, phase: 1, title: 'Rheum/Renal — Q Solve · Consolidation',                   subject: 'Rheum/Renal',   eQty: 40, isMilestone: true },
  { id: 38, phase: 1, title: 'Dermatology 1 — Watch · Notes',                           subject: 'Dermatology',   eQty: 10, isMilestone: false },
  { id: 39, phase: 1, title: 'Dermatology 2 — Consolidation',                           subject: 'Dermatology',   eQty: 40, isMilestone: true },
  { id: 40, phase: 1, title: 'Hematology — Watch · Notes',                              subject: 'Hematology',    eQty: 40, isMilestone: true },
  { id: 41, phase: 1, title: 'Ethics — Watch · Notes',                                  subject: 'Ethics',        eQty: 40, isMilestone: true },
  { id: 42, phase: 1, title: 'Statistics — Watch · Notes',                              subject: 'Statistics',    eQty: 40, isMilestone: true },
  { id: 43, phase: 1, title: 'CTG + ABG — Watch · Notes',                               subject: 'CTG/ABG',       eQty: 40, isMilestone: true },
  { id: 44, phase: 1, title: 'Left Out Topics + Phase 1 Final Review',                  subject: 'ALL',           eQty: 50, isMilestone: false },

  // Phase 2 (id 45–67)
  { id: 45, phase: 2, title: 'Recall Class 1 + 2 — Pause Protocol · Gap Analysis',      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 46, phase: 2, title: 'Recall Class 3 + 4',                                      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 47, phase: 2, title: 'Recall Class 5 + Random Q Solve 1',                       subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 48, phase: 2, title: 'Recall Class 6 + 7',                                      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 49, phase: 2, title: '⚡ MOCK EXAM 1 — 100q Timed · Full Analysis',              subject: 'ALL',   eQty: 100, isMilestone: true },
  { id: 50, phase: 2, title: 'Recall Class 8 + 9',                                      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 51, phase: 2, title: 'Recall Class 10 + Random Q Solve 2',                      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 52, phase: 2, title: 'Recall Class 11 + 12',                                    subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 53, phase: 2, title: 'Recall Class 13 + 14',                                    subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 54, phase: 2, title: 'Recall Class 15 + Random Q Solve 3',                      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 55, phase: 2, title: '⚡ MOCK EXAM 2 — 100q Timed',                              subject: 'ALL',   eQty: 100, isMilestone: true },
  { id: 56, phase: 2, title: 'Recall Class 16 + 17 + Recalls Month 3 Day 1',            subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 57, phase: 2, title: 'Recall Class 18 + Random Q Solve 4',                      subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 58, phase: 2, title: 'Recall Class 19 + 20 + Recalls Month 3 Day 2',            subject: 'Mixed', eQty: 40, isMilestone: false },
  { id: 59, phase: 2, title: 'Recall Class 21 + 22',                                    subject: 'Mixed', eQty: 30, isMilestone: false },
  { id: 60, phase: 2, title: 'Recall Class 23 + Random Q Solve 5',                      subject: 'Mixed', eQty: 30, isMilestone: false },
  { id: 61, phase: 2, title: 'Recall Class 24 + 25',                                    subject: 'Mixed', eQty: 30, isMilestone: false },
  { id: 62, phase: 2, title: 'Recall Class 26 + 27',                                    subject: 'Mixed', eQty: 30, isMilestone: true },
  { id: 63, phase: 2, title: 'Recall Class 28 + Random Q Solve 6',                      subject: 'Mixed', eQty: 30, isMilestone: false },
  { id: 64, phase: 2, title: 'Recall Class 29 + 30',                                    subject: 'Mixed', eQty: 20, isMilestone: false },
  { id: 65, phase: 2, title: 'Recall Class 31 + 32',                                    subject: 'Mixed', eQty: 20, isMilestone: false },
  { id: 66, phase: 2, title: 'Recall Class 33 + 34 + Random Q Solve 7',                 subject: 'Mixed', eQty: 20, isMilestone: false },
  { id: 67, phase: 2, title: 'Recall Class 35 — FINAL Recall Class',                    subject: 'Mixed', eQty: 20, isMilestone: true },

  // Phase 3 (id 68–77)
  { id: 68, phase: 3, title: 'Recall Questions Month 2 — Day 6',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 69, phase: 3, title: 'Recall Questions Month 2 — Day 7 COMPLETE',               subject: 'RECALLS', eQty: 20, isMilestone: true },
  { id: 70, phase: 3, title: '⚡ MOCK EXAM 3 — 150q Full AMC Simulation',                subject: 'ALL',     eQty: 150, isMilestone: true },
  { id: 71, phase: 3, title: 'Recall Questions Month 1 — Day 1',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 72, phase: 3, title: 'Recall Questions Month 1 — Day 2',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 73, phase: 3, title: 'Recall Questions Month 1 — Day 3',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 74, phase: 3, title: 'Recall Questions Month 1 — Day 4',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 75, phase: 3, title: 'Recall Questions Month 1 — Day 5',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 76, phase: 3, title: 'Recall Questions Month 1 — Day 6',                        subject: 'RECALLS', eQty: 20, isMilestone: false },
  { id: 77, phase: 3, title: 'Recall Qs Month 1 Day 7 · ALL 2250q COMPLETE',            subject: 'RECALLS', eQty: 20, isMilestone: true },
];

export const SUBJECTS = [
  { name: 'Endocrinology',  milestoneTaskId: 1  },
  { name: 'Cardiology',     milestoneTaskId: 6  },
  { name: 'Pediatrics',     milestoneTaskId: 14 },
  { name: 'Surgery',        milestoneTaskId: 15 },
  { name: 'Respiratory',    milestoneTaskId: 18 },
  { name: 'Psychiatry',     milestoneTaskId: 23 },
  { name: 'ENT',            milestoneTaskId: 24 },
  { name: 'GIT',            milestoneTaskId: 26 },
  { name: 'Ophthalmology',  milestoneTaskId: 27 },
  { name: 'Obs/Gynae',      milestoneTaskId: 32 },
  { name: 'Neurology',      milestoneTaskId: 33 },
  { name: 'Orthopedics',    milestoneTaskId: 34 },
  { name: 'Rheum/Renal',    milestoneTaskId: 37 },
  { name: 'Dermatology',    milestoneTaskId: 39 },
  { name: 'Hematology',     milestoneTaskId: 40 },
  { name: 'Ethics',         milestoneTaskId: 41 },
  { name: 'Statistics',     milestoneTaskId: 42 },
  { name: 'CTG/ABG',        milestoneTaskId: 43 },
];

export const SR_INTERVALS = { blackout: 3, hard: 7, medium: 14, easy: 21 };

export const CD_PATH_BLOCKS = [
  { label: 'Block 1', time: '5:30–6:20am' },
  { label: 'Block 2', time: '6:30–7:20am' },
  { label: 'Block 3', time: '7:30–8:20am' },
  { label: 'Block 4', time: '8:30–9:20am' },
  { label: 'Block 5', time: '9:50–10:40am' },
  { label: 'Block 6', time: '10:50–11:40am' },
  { label: 'Block 7', time: '3:00–3:50pm' },
  { label: 'Block 8', time: '4:05–4:55pm' },
  { label: 'Block 9', time: '5:05–5:55pm' },
  { label: 'Block 10', time: '6:15–7:05pm' },
  { label: 'Block 11', time: '7:35–8:20pm' },
];

export const GYM_BLOCKS = [
  { label: 'Block 1', time: '5:30–6:20am' },
  { label: 'Block 2', time: '6:30–7:20am' },
  { label: 'Block 3', time: '7:30–8:20am' },
  { label: 'Block 4', time: '8:30–9:20am' },
  { label: 'Block 5', time: '9:50–10:40am' },
  { label: 'Block 6', time: '10:50–11:40am' },
  { label: 'Block 7', time: '11:50–12:40pm' },
  { label: 'Block 8', time: '1:45–2:35pm' },
  { label: 'Block 9', time: '2:45–3:35pm' },
  { label: 'Block 10', time: '6:30–7:20pm' },
  { label: 'Block 11', time: '7:30–8:20pm' },
];
