// Default seed data — used only for first-login seeding.
// Live screens use Supabase tables, not these constants directly.

export const DEFAULT_SETTINGS = {
  exam_name: 'AMC MCQ',
  exam_date: '2026-08-17',
  study_start_date: '2026-05-04',
  question_bank_name: 'eMedici',
  sr1_interval: 7,
  sr2_multiplier: 1.5,
  sr3_multiplier: 2.0,
  grace_period_days: 2,
  rest_days_per_month: 6,
  tier1_sr_hits: 3,
  tier2_sr_hits: 2,
  tier3_sr_hits: 1,
  daily_question_target: 40,
};

export const DEFAULT_PHASES = [
  { name: 'Phase 1 — Subject Coverage',             description: 'Watch, note-take, and consolidate each subject', sort_order: 1 },
  { name: 'Phase 2 — Recall Classes & Mixed Practice', description: 'Recall classes and mixed question solving',     sort_order: 2 },
  { name: 'Phase 3 — Final Recall & Mock Exams',    description: 'Final recall questions and full AMC simulations', sort_order: 3 },
];

export const DEFAULT_SUBJECTS = [
  { name: 'Endocrinology', blueprint_category: 'Adult Medicine',  class_count: 1, emedici_target: 40, tier: 1, sr_hits: 3, sort_order: 1  },
  { name: 'Cardiology',    blueprint_category: 'Adult Medicine',  class_count: 4, emedici_target: 40, tier: 1, sr_hits: 3, sort_order: 2  },
  { name: 'Pediatrics',    blueprint_category: 'Child Health',    class_count: 7, emedici_target: 40, tier: 1, sr_hits: 3, sort_order: 3  },
  { name: 'Surgery',       blueprint_category: 'Adult Surgery',   class_count: 1, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 4  },
  { name: 'Respiratory',   blueprint_category: 'Adult Medicine',  class_count: 2, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 5  },
  { name: 'Psychiatry',    blueprint_category: 'Mental Health',   class_count: 3, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 6  },
  { name: 'ENT',           blueprint_category: 'Adult Surgery',   class_count: 1, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 7  },
  { name: 'GIT',           blueprint_category: 'Adult Medicine',  class_count: 2, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 8  },
  { name: 'Ophthalmology', blueprint_category: 'Adult Surgery',   class_count: 1, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 9  },
  { name: 'Obs/Gynae',     blueprint_category: "Women's Health",  class_count: 4, emedici_target: 40, tier: 1, sr_hits: 3, sort_order: 10 },
  { name: 'Neurology',     blueprint_category: 'Adult Medicine',  class_count: 1, emedici_target: 40, tier: 1, sr_hits: 3, sort_order: 11 },
  { name: 'Orthopedics',   blueprint_category: 'Adult Surgery',   class_count: 2, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 12 },
  { name: 'Rheum/Renal',   blueprint_category: 'Adult Medicine',  class_count: 2, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 13 },
  { name: 'Dermatology',   blueprint_category: 'Adult Medicine',  class_count: 2, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 14 },
  { name: 'Hematology',    blueprint_category: 'Adult Medicine',  class_count: 1, emedici_target: 40, tier: 2, sr_hits: 2, sort_order: 15 },
  { name: 'Ethics',        blueprint_category: 'Ethics',          class_count: 1, emedici_target: 40, tier: 3, sr_hits: 1, sort_order: 16 },
  { name: 'Statistics',    blueprint_category: 'Statistics',      class_count: 1, emedici_target: 40, tier: 3, sr_hits: 1, sort_order: 17 },
  { name: 'CTG/ABG',       blueprint_category: 'Other',           class_count: 1, emedici_target: 40, tier: 3, sr_hits: 1, sort_order: 18 },
];

// 77 default tasks — identical to original plan
// subject field matches DEFAULT_SUBJECTS names for FK mapping
export const DEFAULT_TASKS = [
  { sort_order: 1,  phase: 1, title: 'Endocrinology — Consolidation · Pass 2 · Master Sheet',  subject: 'Endocrinology', emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 2,  phase: 1, title: 'Cardiology 1 — Watch · Notes',                            subject: 'Cardiology',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 3,  phase: 1, title: 'Cardiology 2 — Watch · Notes',                            subject: 'Cardiology',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 4,  phase: 1, title: 'ECG 1 — Watch · Notes',                                   subject: 'Cardiology',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 5,  phase: 1, title: 'Cardiology Q Solve — Watch · Notes',                      subject: 'Cardiology',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 6,  phase: 1, title: 'Cardiology — Consolidation · Pass 2 · Master Sheet',      subject: 'Cardiology',    emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 7,  phase: 1, title: 'Pediatrics 1 — Watch · Notes',                            subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 8,  phase: 1, title: 'Pediatrics 2 — Watch · Notes',                            subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 9,  phase: 1, title: 'Pediatrics 3 — Watch · Notes',                            subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 10, phase: 1, title: 'Pediatrics 4 — Watch · Notes',                            subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 11, phase: 1, title: 'Pedi Special Problem 1 — Watch · Notes',                  subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 12, phase: 1, title: 'Pedi Q Solve 1 — Watch · Notes',                          subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 13, phase: 1, title: 'Pedi Q Solve 2 — Watch · Notes',                          subject: 'Pediatrics',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 14, phase: 1, title: 'Pediatrics — Consolidation · Pass 2 · Master Sheet',      subject: 'Pediatrics',    emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 15, phase: 1, title: 'Surgery — Watch · Notes',                                 subject: 'Surgery',       emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 16, phase: 1, title: 'Respiratory 1 — Watch · Notes',                           subject: 'Respiratory',   emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 17, phase: 1, title: 'Respiratory 2 — Watch · Notes',                           subject: 'Respiratory',   emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 18, phase: 1, title: 'Respiratory — Q Solve · Consolidation',                   subject: 'Respiratory',   emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 19, phase: 1, title: 'Orthopedics 1 — Watch · Notes',                           subject: 'Orthopedics',   emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 20, phase: 1, title: 'Psychiatry 1 — Watch · Notes',                            subject: 'Psychiatry',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 21, phase: 1, title: 'Psychiatry 2 — Watch · Notes',                            subject: 'Psychiatry',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 22, phase: 1, title: 'Psychiatry 3 — Watch · Notes',                            subject: 'Psychiatry',    emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 23, phase: 1, title: 'Psychiatry — Q Solve · Consolidation',                    subject: 'Psychiatry',    emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 24, phase: 1, title: 'ENT — Watch · Notes',                                     subject: 'ENT',           emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 25, phase: 1, title: 'GIT 1 — Watch · Notes',                                   subject: 'GIT',           emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 26, phase: 1, title: 'GIT 2 — Watch · Notes · Consolidation',                   subject: 'GIT',           emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 27, phase: 1, title: 'Ophthalmology — Watch · Notes',                           subject: 'Ophthalmology', emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 28, phase: 1, title: 'Gynae 1 — Watch · Notes',                                 subject: 'Obs/Gynae',     emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 29, phase: 1, title: 'Gynae 2 — Watch · Notes',                                 subject: 'Obs/Gynae',     emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 30, phase: 1, title: 'Obstetrics 1 — Watch · Notes',                            subject: 'Obs/Gynae',     emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 31, phase: 1, title: 'Obstetrics 2 — Watch · Notes',                            subject: 'Obs/Gynae',     emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 32, phase: 1, title: 'O&G — Consolidation · Pass 2 · Master Sheet',             subject: 'Obs/Gynae',     emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 33, phase: 1, title: 'Neurology — Watch · Notes',                               subject: 'Neurology',     emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 34, phase: 1, title: 'Orthopedics 2 — Watch · Notes',                           subject: 'Orthopedics',   emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 35, phase: 1, title: 'Rheumatology 1 — Watch · Notes',                          subject: 'Rheum/Renal',   emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 36, phase: 1, title: 'Rheum + Renal 2 — Watch · Notes',                         subject: 'Rheum/Renal',   emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 37, phase: 1, title: 'Rheum/Renal — Q Solve · Consolidation',                   subject: 'Rheum/Renal',   emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 38, phase: 1, title: 'Dermatology 1 — Watch · Notes',                           subject: 'Dermatology',   emedici_qty: 10, is_milestone: false, is_mock: false },
  { sort_order: 39, phase: 1, title: 'Dermatology 2 — Consolidation',                           subject: 'Dermatology',   emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 40, phase: 1, title: 'Hematology — Watch · Notes',                              subject: 'Hematology',    emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 41, phase: 1, title: 'Ethics — Watch · Notes',                                  subject: 'Ethics',        emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 42, phase: 1, title: 'Statistics — Watch · Notes',                              subject: 'Statistics',    emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 43, phase: 1, title: 'CTG + ABG — Watch · Notes',                               subject: 'CTG/ABG',       emedici_qty: 40, is_milestone: true,  is_mock: false },
  { sort_order: 44, phase: 1, title: 'Left Out Topics + Phase 1 Final Review',                  subject: null,            emedici_qty: 50, is_milestone: false, is_mock: false },
  { sort_order: 45, phase: 2, title: 'Recall Class 1 + 2 — Pause Protocol · Gap Analysis',      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 46, phase: 2, title: 'Recall Class 3 + 4',                                      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 47, phase: 2, title: 'Recall Class 5 + Random Q Solve 1',                       subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 48, phase: 2, title: 'Recall Class 6 + 7',                                      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 49, phase: 2, title: '⚡ MOCK EXAM 1 — 100q Timed · Full Analysis',              subject: null,            emedici_qty: 100, is_milestone: true,  is_mock: true  },
  { sort_order: 50, phase: 2, title: 'Recall Class 8 + 9',                                      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 51, phase: 2, title: 'Recall Class 10 + Random Q Solve 2',                      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 52, phase: 2, title: 'Recall Class 11 + 12',                                    subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 53, phase: 2, title: 'Recall Class 13 + 14',                                    subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 54, phase: 2, title: 'Recall Class 15 + Random Q Solve 3',                      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 55, phase: 2, title: '⚡ MOCK EXAM 2 — 100q Timed',                              subject: null,            emedici_qty: 100, is_milestone: true,  is_mock: true  },
  { sort_order: 56, phase: 2, title: 'Recall Class 16 + 17 + Recalls Month 3 Day 1',            subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 57, phase: 2, title: 'Recall Class 18 + Random Q Solve 4',                      subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 58, phase: 2, title: 'Recall Class 19 + 20 + Recalls Month 3 Day 2',            subject: null,            emedici_qty: 40, is_milestone: false, is_mock: false },
  { sort_order: 59, phase: 2, title: 'Recall Class 21 + 22',                                    subject: null,            emedici_qty: 30, is_milestone: false, is_mock: false },
  { sort_order: 60, phase: 2, title: 'Recall Class 23 + Random Q Solve 5',                      subject: null,            emedici_qty: 30, is_milestone: false, is_mock: false },
  { sort_order: 61, phase: 2, title: 'Recall Class 24 + 25',                                    subject: null,            emedici_qty: 30, is_milestone: false, is_mock: false },
  { sort_order: 62, phase: 2, title: 'Recall Class 26 + 27',                                    subject: null,            emedici_qty: 30, is_milestone: true,  is_mock: false },
  { sort_order: 63, phase: 2, title: 'Recall Class 28 + Random Q Solve 6',                      subject: null,            emedici_qty: 30, is_milestone: false, is_mock: false },
  { sort_order: 64, phase: 2, title: 'Recall Class 29 + 30',                                    subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 65, phase: 2, title: 'Recall Class 31 + 32',                                    subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 66, phase: 2, title: 'Recall Class 33 + 34 + Random Q Solve 7',                 subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 67, phase: 2, title: 'Recall Class 35 — FINAL Recall Class',                    subject: null,            emedici_qty: 20, is_milestone: true,  is_mock: false },
  { sort_order: 68, phase: 3, title: 'Recall Questions Month 2 — Day 6',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 69, phase: 3, title: 'Recall Questions Month 2 — Day 7 COMPLETE',               subject: null,            emedici_qty: 20, is_milestone: true,  is_mock: false },
  { sort_order: 70, phase: 3, title: '⚡ MOCK EXAM 3 — 150q Full AMC Simulation',                subject: null,            emedici_qty: 150, is_milestone: true,  is_mock: true  },
  { sort_order: 71, phase: 3, title: 'Recall Questions Month 1 — Day 1',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 72, phase: 3, title: 'Recall Questions Month 1 — Day 2',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 73, phase: 3, title: 'Recall Questions Month 1 — Day 3',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 74, phase: 3, title: 'Recall Questions Month 1 — Day 4',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 75, phase: 3, title: 'Recall Questions Month 1 — Day 5',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 76, phase: 3, title: 'Recall Questions Month 1 — Day 6',                        subject: null,            emedici_qty: 20, is_milestone: false, is_mock: false },
  { sort_order: 77, phase: 3, title: 'Recall Qs Month 1 Day 7 · ALL 2250q COMPLETE',            subject: null,            emedici_qty: 20, is_milestone: true,  is_mock: false },
];

export const DEFAULT_SCHEDULE_TEMPLATES = [
  {
    name: 'CD Path Day',
    is_default: false,
    blocks: [
      { label: 'Block 1',  start: '05:30', end: '06:20', type: 'study' },
      { label: 'Block 2',  start: '06:30', end: '07:20', type: 'study' },
      { label: 'Block 3',  start: '07:30', end: '08:20', type: 'study' },
      { label: 'Block 4',  start: '08:30', end: '09:20', type: 'study' },
      { label: 'Block 5',  start: '09:50', end: '10:40', type: 'study' },
      { label: 'Block 6',  start: '10:50', end: '11:40', type: 'study' },
      { label: 'Block 7',  start: '15:00', end: '15:50', type: 'study' },
      { label: 'Block 8',  start: '16:05', end: '16:55', type: 'study' },
      { label: 'Block 9',  start: '17:05', end: '17:55', type: 'study' },
      { label: 'Block 10', start: '18:15', end: '19:05', type: 'study' },
      { label: 'Block 11', start: '19:35', end: '20:20', type: 'study' },
    ],
  },
  {
    name: 'Gym Day',
    is_default: true,
    blocks: [
      { label: 'Block 1',  start: '05:30', end: '06:20', type: 'study' },
      { label: 'Block 2',  start: '06:30', end: '07:20', type: 'study' },
      { label: 'Block 3',  start: '07:30', end: '08:20', type: 'study' },
      { label: 'Block 4',  start: '08:30', end: '09:20', type: 'study' },
      { label: 'Block 5',  start: '09:50', end: '10:40', type: 'study' },
      { label: 'Block 6',  start: '10:50', end: '11:40', type: 'study' },
      { label: 'Block 7',  start: '11:50', end: '12:40', type: 'study' },
      { label: 'Block 8',  start: '13:45', end: '14:35', type: 'study' },
      { label: 'Block 9',  start: '14:45', end: '15:35', type: 'study' },
      { label: 'Block 10', start: '18:30', end: '19:20', type: 'study' },
      { label: 'Block 11', start: '19:30', end: '20:20', type: 'study' },
    ],
  },
];

// 0=Sun,1=Mon,2=Tue,3=Wed,4=Thu,5=Fri,6=Sat
// Mon(1) and Wed(3) = CD Path Day; others = Gym Day
export const DEFAULT_SCHEDULE_ASSIGNMENTS = {
  0: 'Gym Day',
  1: 'CD Path Day',
  2: 'Gym Day',
  3: 'CD Path Day',
  4: 'Gym Day',
  5: 'Gym Day',
  6: 'Gym Day',
};
